version: '3.7'
services:
    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        env_file:
            - .env
        env_file:
            - .env.example
        environment:
            - LOAD_EX: n
            - EXECUTOR: Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/opt/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3